### ISSUE TITLE
Invoking npm.cmd on Windows is failing

### ISSUE THREAD

**Issue by idursun** [kilork/actix-web-static-files#14]
When I run `cargo build` on Windows I get the following error:

```
error: failed to run custom build command for `web v0.1.0 (C:\repositories\rust\myproject\web)`

Caused by:
  process didn't exit successfully: `C:\repositories\rust\myproject\target\debug\build\web-b0554dea23c73a0f\build-script-build` (exit code: 101)
--- stdout
NPM_CMD is npm.cmd
 running npm install npm.cmd in "./assets"

--- stderr
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', web\build.rs:4:5
```

However, the same project compiles just fine on Linux.

The following code reproduced the same error:

```rust
    if let Err(e) = Command::new("npm.cmd")
        .arg("install")
        .current_dir(r#"c:\repositories\rust\myproject\web\assets\"#)
        .status()
    {
        eprintln!("Cannot execute install: {:?}", e);
    }
```
I think it is due to the fact that `npm.cmd` needs to set some variables and probably update PATH prior to running in the command shell. 

The following code seems to work without any problems.

```rust
    if let Err(e) = Command::new("cmd")
        .arg("/c")
        .arg("npm.cmd")
        .arg("install")
        .current_dir(r#"c:\repositories\rust\mdreader\web\assets\"#)
        .status()
    {
        eprintln!("Cannot execute install: {:?}", e);
    }
```

**Comment by kilork** [comment]
Hi! Thank you for for this report and proposed solution. I have feeling, that if npm ran once before it is run from cargo - this thing somehow does not happen.

But if your solution just works I consider this better fix, as trying to analyse why this happens.

**Comment by idursun** [comment]
Hi @kilork,

Running npm first before cargo seems to be working fine only because error messages are silenced by cargo.

If I run `cargo build -vv` then I see the same errors being printed by npm.

**Comment by idursun** [comment]
Thanks @kilork!

**Comment by kilork** [comment]
@idursun thank you, I basically just followed you :)
